[package]

name = "wiki"
version = "0.0.1"
authors = [ "Andrea Coato <andrea.coato@gmail.com>" ]

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indicatif = "0.17"
colored = "2.0"

